### ISSUE TITLE
npm run electron:build出来的程序，打开空白的，没有内容

### ISSUE THREAD

**Issue by zonghongyan** [QiaoGen/vue-personal-projects#1]
<img width="798" alt="截屏2023-08-27 17 07 19" src="https://github.com/QiaoGen/vue-personal-projects/assets/16010239/c0f35472-6776-49db-a406-c2e7258be7db">

**Comment by QiaoGen** [comment]
ok sign not show. You should use 'yarn electron:serve' command to checkout at first. First page will show available serialport    list.
